/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse struct {
	Application   *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication `json:"application,omitempty"`
	ApplicationId *string                                                                        `json:"application_id,omitempty"`
	CreatedAt     *string                                                                        `json:"created_at,omitempty"`
	Id            *string                                                                        `json:"id,omitempty"`
	Run           *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun         `json:"run,omitempty"`
	RunId         *string                                                                        `json:"run_id,omitempty"`
	ShortName     *string                                                                        `json:"short_name,omitempty"`
	Url           *string                                                                        `json:"url,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponseWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponseWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse{}
	return &this
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetApplication() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication {
	if o == nil || IsNil(o.Application) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetApplicationOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication, bool) {
	if o == nil || IsNil(o.Application) {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasApplication() bool {
	if o != nil && !IsNil(o.Application) {
		return true
	}

	return false
}

// SetApplication gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication and assigns it to the Application field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetApplication(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication) {
	o.Application = &v
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetApplicationId() string {
	if o == nil || IsNil(o.ApplicationId) {
		var ret string
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetApplicationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationId) {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasApplicationId() bool {
	if o != nil && !IsNil(o.ApplicationId) {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given string and assigns it to the ApplicationId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetApplicationId(v string) {
	o.ApplicationId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetId(v string) {
	o.Id = &v
}

// GetRun returns the Run field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetRun() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun {
	if o == nil || IsNil(o.Run) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun
		return ret
	}
	return *o.Run
}

// GetRunOk returns a tuple with the Run field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetRunOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun, bool) {
	if o == nil || IsNil(o.Run) {
		return nil, false
	}
	return o.Run, true
}

// HasRun returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasRun() bool {
	if o != nil && !IsNil(o.Run) {
		return true
	}

	return false
}

// SetRun gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun and assigns it to the Run field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetRun(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun) {
	o.Run = &v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetRunId(v string) {
	o.RunId = &v
}

// GetShortName returns the ShortName field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetShortName() string {
	if o == nil || IsNil(o.ShortName) {
		var ret string
		return ret
	}
	return *o.ShortName
}

// GetShortNameOk returns a tuple with the ShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetShortNameOk() (*string, bool) {
	if o == nil || IsNil(o.ShortName) {
		return nil, false
	}
	return o.ShortName, true
}

// HasShortName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasShortName() bool {
	if o != nil && !IsNil(o.ShortName) {
		return true
	}

	return false
}

// SetShortName gets a reference to the given string and assigns it to the ShortName field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetShortName(v string) {
	o.ShortName = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) SetUrl(v string) {
	o.Url = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Application) {
		toSerialize["application"] = o.Application
	}
	if !IsNil(o.ApplicationId) {
		toSerialize["application_id"] = o.ApplicationId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Run) {
		toSerialize["run"] = o.Run
	}
	if !IsNil(o.RunId) {
		toSerialize["run_id"] = o.RunId
	}
	if !IsNil(o.ShortName) {
		toSerialize["short_name"] = o.ShortName
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
