/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob struct {
	CreatedAt          *string                                                                      `json:"created_at,omitempty"`
	DataPlaneExecName  *string                                                                      `json:"data_plane_exec_name,omitempty"`
	DataPlaneJobName   *string                                                                      `json:"data_plane_job_name,omitempty"`
	Id                 *string                                                                      `json:"id,omitempty"`
	Name               *string                                                                      `json:"name,omitempty"`
	RunId              *string                                                                      `json:"run_id,omitempty"`
	SequenceNumber     *int                                                                         `json:"sequence_number,omitempty"`
	StageId            *string                                                                      `json:"stage_id,omitempty"`
	Status             *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus `json:"status,omitempty"`
	TemporalWorkflowId *string                                                                      `json:"temporal_workflow_id,omitempty"`
	Type               *string                                                                      `json:"type,omitempty"`
	UpdatedAt          *string                                                                      `json:"updated_at,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDataPlaneExecName returns the DataPlaneExecName field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetDataPlaneExecName() string {
	if o == nil || IsNil(o.DataPlaneExecName) {
		var ret string
		return ret
	}
	return *o.DataPlaneExecName
}

// GetDataPlaneExecNameOk returns a tuple with the DataPlaneExecName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetDataPlaneExecNameOk() (*string, bool) {
	if o == nil || IsNil(o.DataPlaneExecName) {
		return nil, false
	}
	return o.DataPlaneExecName, true
}

// HasDataPlaneExecName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasDataPlaneExecName() bool {
	if o != nil && !IsNil(o.DataPlaneExecName) {
		return true
	}

	return false
}

// SetDataPlaneExecName gets a reference to the given string and assigns it to the DataPlaneExecName field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetDataPlaneExecName(v string) {
	o.DataPlaneExecName = &v
}

// GetDataPlaneJobName returns the DataPlaneJobName field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetDataPlaneJobName() string {
	if o == nil || IsNil(o.DataPlaneJobName) {
		var ret string
		return ret
	}
	return *o.DataPlaneJobName
}

// GetDataPlaneJobNameOk returns a tuple with the DataPlaneJobName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetDataPlaneJobNameOk() (*string, bool) {
	if o == nil || IsNil(o.DataPlaneJobName) {
		return nil, false
	}
	return o.DataPlaneJobName, true
}

// HasDataPlaneJobName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasDataPlaneJobName() bool {
	if o != nil && !IsNil(o.DataPlaneJobName) {
		return true
	}

	return false
}

// SetDataPlaneJobName gets a reference to the given string and assigns it to the DataPlaneJobName field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetDataPlaneJobName(v string) {
	o.DataPlaneJobName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetName(v string) {
	o.Name = &v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetRunId(v string) {
	o.RunId = &v
}

// GetSequenceNumber returns the SequenceNumber field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetSequenceNumber() int {
	if o == nil || IsNil(o.SequenceNumber) {
		var ret int
		return ret
	}
	return *o.SequenceNumber
}

// GetSequenceNumberOk returns a tuple with the SequenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetSequenceNumberOk() (*int, bool) {
	if o == nil || IsNil(o.SequenceNumber) {
		return nil, false
	}
	return o.SequenceNumber, true
}

// HasSequenceNumber returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasSequenceNumber() bool {
	if o != nil && !IsNil(o.SequenceNumber) {
		return true
	}

	return false
}

// SetSequenceNumber gets a reference to the given int and assigns it to the SequenceNumber field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetSequenceNumber(v int) {
	o.SequenceNumber = &v
}

// GetStageId returns the StageId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetStageId() string {
	if o == nil || IsNil(o.StageId) {
		var ret string
		return ret
	}
	return *o.StageId
}

// GetStageIdOk returns a tuple with the StageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetStageIdOk() (*string, bool) {
	if o == nil || IsNil(o.StageId) {
		return nil, false
	}
	return o.StageId, true
}

// HasStageId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasStageId() bool {
	if o != nil && !IsNil(o.StageId) {
		return true
	}

	return false
}

// SetStageId gets a reference to the given string and assigns it to the StageId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetStageId(v string) {
	o.StageId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetStatus() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus {
	if o == nil || IsNil(o.Status) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetStatusOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus and assigns it to the Status field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetStatus(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) {
	o.Status = &v
}

// GetTemporalWorkflowId returns the TemporalWorkflowId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetTemporalWorkflowId() string {
	if o == nil || IsNil(o.TemporalWorkflowId) {
		var ret string
		return ret
	}
	return *o.TemporalWorkflowId
}

// GetTemporalWorkflowIdOk returns a tuple with the TemporalWorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetTemporalWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemporalWorkflowId) {
		return nil, false
	}
	return o.TemporalWorkflowId, true
}

// HasTemporalWorkflowId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasTemporalWorkflowId() bool {
	if o != nil && !IsNil(o.TemporalWorkflowId) {
		return true
	}

	return false
}

// SetTemporalWorkflowId gets a reference to the given string and assigns it to the TemporalWorkflowId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetTemporalWorkflowId(v string) {
	o.TemporalWorkflowId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetType(v string) {
	o.Type = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DataPlaneExecName) {
		toSerialize["data_plane_exec_name"] = o.DataPlaneExecName
	}
	if !IsNil(o.DataPlaneJobName) {
		toSerialize["data_plane_job_name"] = o.DataPlaneJobName
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RunId) {
		toSerialize["run_id"] = o.RunId
	}
	if !IsNil(o.SequenceNumber) {
		toSerialize["sequence_number"] = o.SequenceNumber
	}
	if !IsNil(o.StageId) {
		toSerialize["stage_id"] = o.StageId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TemporalWorkflowId) {
		toSerialize["temporal_workflow_id"] = o.TemporalWorkflowId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
