/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate struct {
	Branch  string  `json:"branch"`
	Name    *string `json:"name,omitempty"`
	SpaceId string  `json:"space_id"`
}

type _GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate(branch string, spaceId string) *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate{}
	this.Branch = branch
	this.SpaceId = spaceId
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdateWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdateWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate{}
	return &this
}

// GetBranch returns the Branch field value
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) SetBranch(v string) {
	o.Branch = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) SetName(v string) {
	o.Name = &v
}

// GetSpaceId returns the SpaceId field value
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) GetSpaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) GetSpaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpaceId, true
}

// SetSpaceId sets field value
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) SetSpaceId(v string) {
	o.SpaceId = v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["branch"] = o.Branch
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["space_id"] = o.SpaceId
	return toSerialize, nil
}

func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"branch",
		"space_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate := _GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate)

	if err != nil {
		return err
	}

	*o = GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate(varGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate)

	return err
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
