/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline struct {
	Config            *string                                                                              `json:"config,omitempty"`
	ConfigStorageType *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType `json:"config_storage_type,omitempty"`
	CreatedAt         *string                                                                              `json:"created_at,omitempty"`
	CreatorId         *string                                                                              `json:"creator_id,omitempty"`
	EnvironmentId     *string                                                                              `json:"environment_id,omitempty"`
	Id                *string                                                                              `json:"id,omitempty"`
	// Deprecated
	ManifestName      *string                                                                              `json:"manifest_name,omitempty"`
	Name              *string                                                                              `json:"name,omitempty"`
	ProjectId         *string                                                                              `json:"project_id,omitempty"`
	RepoConfigStorage *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage `json:"repo_config_storage,omitempty"`
	// Deprecated
	RepositoryId *string                                                                         `json:"repository_id,omitempty"`
	Type         *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType `json:"type,omitempty"`
	UpdatedAt    *string                                                                         `json:"updated_at,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetConfig() string {
	if o == nil || IsNil(o.Config) {
		var ret string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetConfigOk() (*string, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given string and assigns it to the Config field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetConfig(v string) {
	o.Config = &v
}

// GetConfigStorageType returns the ConfigStorageType field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetConfigStorageType() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType {
	if o == nil || IsNil(o.ConfigStorageType) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType
		return ret
	}
	return *o.ConfigStorageType
}

// GetConfigStorageTypeOk returns a tuple with the ConfigStorageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetConfigStorageTypeOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType, bool) {
	if o == nil || IsNil(o.ConfigStorageType) {
		return nil, false
	}
	return o.ConfigStorageType, true
}

// HasConfigStorageType returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasConfigStorageType() bool {
	if o != nil && !IsNil(o.ConfigStorageType) {
		return true
	}

	return false
}

// SetConfigStorageType gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType and assigns it to the ConfigStorageType field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetConfigStorageType(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) {
	o.ConfigStorageType = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetCreatorId returns the CreatorId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetCreatorId() string {
	if o == nil || IsNil(o.CreatorId) {
		var ret string
		return ret
	}
	return *o.CreatorId
}

// GetCreatorIdOk returns a tuple with the CreatorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetCreatorIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatorId) {
		return nil, false
	}
	return o.CreatorId, true
}

// HasCreatorId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasCreatorId() bool {
	if o != nil && !IsNil(o.CreatorId) {
		return true
	}

	return false
}

// SetCreatorId gets a reference to the given string and assigns it to the CreatorId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetCreatorId(v string) {
	o.CreatorId = &v
}

// GetEnvironmentId returns the EnvironmentId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetEnvironmentId() string {
	if o == nil || IsNil(o.EnvironmentId) {
		var ret string
		return ret
	}
	return *o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetEnvironmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentId) {
		return nil, false
	}
	return o.EnvironmentId, true
}

// HasEnvironmentId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasEnvironmentId() bool {
	if o != nil && !IsNil(o.EnvironmentId) {
		return true
	}

	return false
}

// SetEnvironmentId gets a reference to the given string and assigns it to the EnvironmentId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetEnvironmentId(v string) {
	o.EnvironmentId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetId(v string) {
	o.Id = &v
}

// GetManifestName returns the ManifestName field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetManifestName() string {
	if o == nil || IsNil(o.ManifestName) {
		var ret string
		return ret
	}
	return *o.ManifestName
}

// GetManifestNameOk returns a tuple with the ManifestName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetManifestNameOk() (*string, bool) {
	if o == nil || IsNil(o.ManifestName) {
		return nil, false
	}
	return o.ManifestName, true
}

// HasManifestName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasManifestName() bool {
	if o != nil && !IsNil(o.ManifestName) {
		return true
	}

	return false
}

// SetManifestName gets a reference to the given string and assigns it to the ManifestName field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetManifestName(v string) {
	o.ManifestName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetName(v string) {
	o.Name = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetRepoConfigStorage returns the RepoConfigStorage field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetRepoConfigStorage() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage {
	if o == nil || IsNil(o.RepoConfigStorage) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage
		return ret
	}
	return *o.RepoConfigStorage
}

// GetRepoConfigStorageOk returns a tuple with the RepoConfigStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetRepoConfigStorageOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage, bool) {
	if o == nil || IsNil(o.RepoConfigStorage) {
		return nil, false
	}
	return o.RepoConfigStorage, true
}

// HasRepoConfigStorage returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasRepoConfigStorage() bool {
	if o != nil && !IsNil(o.RepoConfigStorage) {
		return true
	}

	return false
}

// SetRepoConfigStorage gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage and assigns it to the RepoConfigStorage field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetRepoConfigStorage(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) {
	o.RepoConfigStorage = &v
}

// GetRepositoryId returns the RepositoryId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetRepositoryId() string {
	if o == nil || IsNil(o.RepositoryId) {
		var ret string
		return ret
	}
	return *o.RepositoryId
}

// GetRepositoryIdOk returns a tuple with the RepositoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetRepositoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryId) {
		return nil, false
	}
	return o.RepositoryId, true
}

// HasRepositoryId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasRepositoryId() bool {
	if o != nil && !IsNil(o.RepositoryId) {
		return true
	}

	return false
}

// SetRepositoryId gets a reference to the given string and assigns it to the RepositoryId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetRepositoryId(v string) {
	o.RepositoryId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetType() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType {
	if o == nil || IsNil(o.Type) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetTypeOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType and assigns it to the Type field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetType(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) {
	o.Type = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.ConfigStorageType) {
		toSerialize["config_storage_type"] = o.ConfigStorageType
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CreatorId) {
		toSerialize["creator_id"] = o.CreatorId
	}
	if !IsNil(o.EnvironmentId) {
		toSerialize["environment_id"] = o.EnvironmentId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ManifestName) {
		toSerialize["manifest_name"] = o.ManifestName
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.RepoConfigStorage) {
		toSerialize["repo_config_storage"] = o.RepoConfigStorage
	}
	if !IsNil(o.RepositoryId) {
		toSerialize["repository_id"] = o.RepositoryId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
