/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList struct {
	Deployments []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse `json:"deployments,omitempty"`
	Total       *int                                                                                      `json:"total,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentListWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentListWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList{}
	return &this
}

// GetDeployments returns the Deployments field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) GetDeployments() []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse {
	if o == nil || IsNil(o.Deployments) {
		var ret []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse
		return ret
	}
	return o.Deployments
}

// GetDeploymentsOk returns a tuple with the Deployments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) GetDeploymentsOk() ([]GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse, bool) {
	if o == nil || IsNil(o.Deployments) {
		return nil, false
	}
	return o.Deployments, true
}

// HasDeployments returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) HasDeployments() bool {
	if o != nil && !IsNil(o.Deployments) {
		return true
	}

	return false
}

// SetDeployments gets a reference to the given []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse and assigns it to the Deployments field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) SetDeployments(v []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentResponse) {
	o.Deployments = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) GetTotal() int {
	if o == nil || IsNil(o.Total) {
		var ret int
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) GetTotalOk() (*int, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int and assigns it to the Total field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) SetTotal(v int) {
	o.Total = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deployments) {
		toSerialize["deployments"] = o.Deployments
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
