/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun struct {
	Id *string `json:"id,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRunWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRunWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) SetId(v string) {
	o.Id = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponsePipelineRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
