/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
	"fmt"
)

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType the model 'GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType'
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType string

// List of git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.ConfigStorageType
const (
	DBConfigStorageType   GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType = "db"
	RepoConfigStorageType GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType = "repo"
)

// All allowed values of GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType enum
var AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageTypeEnumValues = []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType{
	"db",
	"repo",
}

func (v *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType(value)
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType", value)
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageTypeFromValue returns a pointer to a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageTypeFromValue(v string) (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType, error) {
	ev := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType: valid values are %v", v, AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) IsValid() bool {
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.ConfigStorageType value
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) Ptr() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType {
	return &v
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelConfigStorageType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
