/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
	"fmt"
)

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType the model 'GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType'
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType string

// List of git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.PipelineType
const (
	PipelineTypeCICD     GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType = "cicd"
	PipelineTypeWorkflow GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType = "workflow"
)

// All allowed values of GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType enum
var AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineTypeEnumValues = []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType{
	"cicd",
	"workflow",
}

func (v *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType(value)
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType", value)
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineTypeFromValue returns a pointer to a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineTypeFromValue(v string) (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType, error) {
	ev := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType: valid values are %v", v, AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) IsValid() bool {
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.PipelineType value
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) Ptr() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType {
	return &v
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipelineType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
