/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate struct {
	Branch        string  `json:"branch"`
	Name          *string `json:"name,omitempty"`
	RepositoryId  *string `json:"repository_id,omitempty"`
	RepositoryUrl *string `json:"repository_url,omitempty"`
	SpaceId       *string `json:"space_id,omitempty"`
}

type _GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate(branch string) *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate{}
	this.Branch = branch
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreateWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreateWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate{}
	return &this
}

// GetBranch returns the Branch field value
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetBranch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Branch
}

// GetBranchOk returns a tuple with the Branch field value
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetBranchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Branch, true
}

// SetBranch sets field value
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) SetBranch(v string) {
	o.Branch = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) SetName(v string) {
	o.Name = &v
}

// GetRepositoryId returns the RepositoryId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetRepositoryId() string {
	if o == nil || IsNil(o.RepositoryId) {
		var ret string
		return ret
	}
	return *o.RepositoryId
}

// GetRepositoryIdOk returns a tuple with the RepositoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetRepositoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryId) {
		return nil, false
	}
	return o.RepositoryId, true
}

// HasRepositoryId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) HasRepositoryId() bool {
	if o != nil && !IsNil(o.RepositoryId) {
		return true
	}

	return false
}

// SetRepositoryId gets a reference to the given string and assigns it to the RepositoryId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) SetRepositoryId(v string) {
	o.RepositoryId = &v
}

// GetRepositoryUrl returns the RepositoryUrl field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetRepositoryUrl() string {
	if o == nil || IsNil(o.RepositoryUrl) {
		var ret string
		return ret
	}
	return *o.RepositoryUrl
}

// GetRepositoryUrlOk returns a tuple with the RepositoryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetRepositoryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryUrl) {
		return nil, false
	}
	return o.RepositoryUrl, true
}

// HasRepositoryUrl returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) HasRepositoryUrl() bool {
	if o != nil && !IsNil(o.RepositoryUrl) {
		return true
	}

	return false
}

// SetRepositoryUrl gets a reference to the given string and assigns it to the RepositoryUrl field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) SetRepositoryUrl(v string) {
	o.RepositoryUrl = &v
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) SetSpaceId(v string) {
	o.SpaceId = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["branch"] = o.Branch
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RepositoryId) {
		toSerialize["repository_id"] = o.RepositoryId
	}
	if !IsNil(o.RepositoryUrl) {
		toSerialize["repository_url"] = o.RepositoryUrl
	}
	if !IsNil(o.SpaceId) {
		toSerialize["space_id"] = o.SpaceId
	}
	return toSerialize, nil
}

func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"branch",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate := _GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate)

	if err != nil {
		return err
	}

	*o = GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate(varGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate)

	return err
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationRequestApplicationCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
