/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
	"fmt"
)

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus the model 'GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus'
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus string

// List of git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.JobStatus
const (
	JobStatusEmpty    GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus = ""
	JobStatusPending  GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus = "pending"
	JobStatusRunning  GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus = "running"
	JobStatusDone     GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus = "done"
	JobStatusCanceled GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus = "canceled"
	JobStatusFailed   GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus = "failed"
)

// All allowed values of GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus enum
var AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatusEnumValues = []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus{
	"",
	"pending",
	"running",
	"done",
	"canceled",
	"failed",
}

func (v *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus(value)
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus", value)
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatusFromValue returns a pointer to a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatusFromValue(v string) (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus, error) {
	ev := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus: valid values are %v", v, AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) IsValid() bool {
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.JobStatus value
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) Ptr() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus {
	return &v
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
