/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate struct {
	Branch        *string                                                                `json:"branch,omitempty"`
	CreatedAt     *string                                                                `json:"created_at,omitempty"`
	Id            *string                                                                `json:"id,omitempty"`
	Name          *string                                                                `json:"name,omitempty"`
	PipelineId    *string                                                                `json:"pipeline_id,omitempty"`
	ProjectId     *string                                                                `json:"project_id,omitempty"`
	RepositoryId  *string                                                                `json:"repository_id,omitempty"`
	RepositoryUrl *string                                                                `json:"repository_url,omitempty"`
	Run           *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun `json:"run,omitempty"`
	RunId         *string                                                                `json:"run_id,omitempty"`
	SpaceId       *string                                                                `json:"space_id,omitempty"`
	Status        *string                                                                `json:"status,omitempty"`
	TemplateId    *string                                                                `json:"template_id,omitempty"`
	UpdatedAt     *string                                                                `json:"updated_at,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreateWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreateWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate{}
	return &this
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetBranch(v string) {
	o.Branch = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetName(v string) {
	o.Name = &v
}

// GetPipelineId returns the PipelineId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetPipelineId() string {
	if o == nil || IsNil(o.PipelineId) {
		var ret string
		return ret
	}
	return *o.PipelineId
}

// GetPipelineIdOk returns a tuple with the PipelineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetPipelineIdOk() (*string, bool) {
	if o == nil || IsNil(o.PipelineId) {
		return nil, false
	}
	return o.PipelineId, true
}

// HasPipelineId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasPipelineId() bool {
	if o != nil && !IsNil(o.PipelineId) {
		return true
	}

	return false
}

// SetPipelineId gets a reference to the given string and assigns it to the PipelineId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetPipelineId(v string) {
	o.PipelineId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetRepositoryId returns the RepositoryId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRepositoryId() string {
	if o == nil || IsNil(o.RepositoryId) {
		var ret string
		return ret
	}
	return *o.RepositoryId
}

// GetRepositoryIdOk returns a tuple with the RepositoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRepositoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryId) {
		return nil, false
	}
	return o.RepositoryId, true
}

// HasRepositoryId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasRepositoryId() bool {
	if o != nil && !IsNil(o.RepositoryId) {
		return true
	}

	return false
}

// SetRepositoryId gets a reference to the given string and assigns it to the RepositoryId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetRepositoryId(v string) {
	o.RepositoryId = &v
}

// GetRepositoryUrl returns the RepositoryUrl field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRepositoryUrl() string {
	if o == nil || IsNil(o.RepositoryUrl) {
		var ret string
		return ret
	}
	return *o.RepositoryUrl
}

// GetRepositoryUrlOk returns a tuple with the RepositoryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRepositoryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryUrl) {
		return nil, false
	}
	return o.RepositoryUrl, true
}

// HasRepositoryUrl returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasRepositoryUrl() bool {
	if o != nil && !IsNil(o.RepositoryUrl) {
		return true
	}

	return false
}

// SetRepositoryUrl gets a reference to the given string and assigns it to the RepositoryUrl field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetRepositoryUrl(v string) {
	o.RepositoryUrl = &v
}

// GetRun returns the Run field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRun() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun {
	if o == nil || IsNil(o.Run) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun
		return ret
	}
	return *o.Run
}

// GetRunOk returns a tuple with the Run field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRunOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun, bool) {
	if o == nil || IsNil(o.Run) {
		return nil, false
	}
	return o.Run, true
}

// HasRun returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasRun() bool {
	if o != nil && !IsNil(o.Run) {
		return true
	}

	return false
}

// SetRun gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun and assigns it to the Run field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetRun(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun) {
	o.Run = &v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetRunId(v string) {
	o.RunId = &v
}

// GetSpaceId returns the SpaceId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetSpaceId() string {
	if o == nil || IsNil(o.SpaceId) {
		var ret string
		return ret
	}
	return *o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetSpaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpaceId) {
		return nil, false
	}
	return o.SpaceId, true
}

// HasSpaceId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasSpaceId() bool {
	if o != nil && !IsNil(o.SpaceId) {
		return true
	}

	return false
}

// SetSpaceId gets a reference to the given string and assigns it to the SpaceId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetSpaceId(v string) {
	o.SpaceId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetStatus(v string) {
	o.Status = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PipelineId) {
		toSerialize["pipeline_id"] = o.PipelineId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.RepositoryId) {
		toSerialize["repository_id"] = o.RepositoryId
	}
	if !IsNil(o.RepositoryUrl) {
		toSerialize["repository_url"] = o.RepositoryUrl
	}
	if !IsNil(o.Run) {
		toSerialize["run"] = o.Run
	}
	if !IsNil(o.RunId) {
		toSerialize["run_id"] = o.RunId
	}
	if !IsNil(o.SpaceId) {
		toSerialize["space_id"] = o.SpaceId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
