/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList struct {
	Applications []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication `json:"applications,omitempty"`
	Total        *int                                                                            `json:"total,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationListWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationListWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList{}
	return &this
}

// GetApplications returns the Applications field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) GetApplications() []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication {
	if o == nil || IsNil(o.Applications) {
		var ret []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication
		return ret
	}
	return o.Applications
}

// GetApplicationsOk returns a tuple with the Applications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) GetApplicationsOk() ([]GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication, bool) {
	if o == nil || IsNil(o.Applications) {
		return nil, false
	}
	return o.Applications, true
}

// HasApplications returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) HasApplications() bool {
	if o != nil && !IsNil(o.Applications) {
		return true
	}

	return false
}

// SetApplications gets a reference to the given []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication and assigns it to the Applications field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) SetApplications(v []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication) {
	o.Applications = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) GetTotal() int {
	if o == nil || IsNil(o.Total) {
		var ret int
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) GetTotalOk() (*int, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int and assigns it to the Total field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) SetTotal(v int) {
	o.Total = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Applications) {
		toSerialize["applications"] = o.Applications
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseApplicationList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
