/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal struct for GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal
type GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal struct {
	// Message is text that can be displayed to the user. It should not contain any specific background information about protocols, databases, programming languages, etc.
	Message *string `json:"message,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal() *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternalWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternalWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) SetMessage(v string) {
	o.Message = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal(val *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsInternal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
