/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment struct {
	Application   *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication `json:"application,omitempty"`
	ApplicationId *string                                                                        `json:"application_id,omitempty"`
	CreatedAt     *string                                                                        `json:"created_at,omitempty"`
	Id            *string                                                                        `json:"id,omitempty"`
	Run           *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun         `json:"run,omitempty"`
	RunId         *string                                                                        `json:"run_id,omitempty"`
	ShortName     *string                                                                        `json:"short_name,omitempty"`
	Url           *string                                                                        `json:"url,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeploymentWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeploymentWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment{}
	return &this
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetApplication() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication {
	if o == nil || IsNil(o.Application) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetApplicationOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication, bool) {
	if o == nil || IsNil(o.Application) {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasApplication() bool {
	if o != nil && !IsNil(o.Application) {
		return true
	}

	return false
}

// SetApplication gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication and assigns it to the Application field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetApplication(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelApplication) {
	o.Application = &v
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetApplicationId() string {
	if o == nil || IsNil(o.ApplicationId) {
		var ret string
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetApplicationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationId) {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasApplicationId() bool {
	if o != nil && !IsNil(o.ApplicationId) {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given string and assigns it to the ApplicationId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetApplicationId(v string) {
	o.ApplicationId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetId(v string) {
	o.Id = &v
}

// GetRun returns the Run field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetRun() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun {
	if o == nil || IsNil(o.Run) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun
		return ret
	}
	return *o.Run
}

// GetRunOk returns a tuple with the Run field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetRunOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun, bool) {
	if o == nil || IsNil(o.Run) {
		return nil, false
	}
	return o.Run, true
}

// HasRun returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasRun() bool {
	if o != nil && !IsNil(o.Run) {
		return true
	}

	return false
}

// SetRun gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun and assigns it to the Run field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetRun(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRun) {
	o.Run = &v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetRunId(v string) {
	o.RunId = &v
}

// GetShortName returns the ShortName field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetShortName() string {
	if o == nil || IsNil(o.ShortName) {
		var ret string
		return ret
	}
	return *o.ShortName
}

// GetShortNameOk returns a tuple with the ShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetShortNameOk() (*string, bool) {
	if o == nil || IsNil(o.ShortName) {
		return nil, false
	}
	return o.ShortName, true
}

// HasShortName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasShortName() bool {
	if o != nil && !IsNil(o.ShortName) {
		return true
	}

	return false
}

// SetShortName gets a reference to the given string and assigns it to the ShortName field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetShortName(v string) {
	o.ShortName = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) SetUrl(v string) {
	o.Url = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Application) {
		toSerialize["application"] = o.Application
	}
	if !IsNil(o.ApplicationId) {
		toSerialize["application_id"] = o.ApplicationId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Run) {
		toSerialize["run"] = o.Run
	}
	if !IsNil(o.RunId) {
		toSerialize["run_id"] = o.RunId
	}
	if !IsNil(o.ShortName) {
		toSerialize["short_name"] = o.ShortName
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
