/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
	"fmt"
)

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus the model 'GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus'
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus string

// List of git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.RunStatus
const (
	RunStatusPending  GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus = "pending"
	RunStatusRunning  GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus = "running"
	RunStatusDone     GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus = "done"
	RunStatusCanceled GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus = "canceled"
	RunStatusFailed   GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus = "failed"
)

// All allowed values of GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus enum
var AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatusEnumValues = []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus{
	"pending",
	"running",
	"done",
	"canceled",
	"failed",
}

func (v *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus(value)
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus", value)
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatusFromValue returns a pointer to a valid GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatusFromValue(v string) (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus, error) {
	ev := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus: valid values are %v", v, AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) IsValid() bool {
	for _, existing := range AllowedGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to git_sbercloud_tech_dsworks_services_pipeline_src_internal_application_model.RunStatus value
func (v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) Ptr() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus {
	return &v
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
