/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// ID UUID v7
	Id        *string                                                                      `json:"id,omitempty"`
	Jobs      []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob      `json:"jobs,omitempty"`
	Name      *string                                                                      `json:"name,omitempty"`
	RunId     *string                                                                      `json:"run_id,omitempty"`
	Status    *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus `json:"status,omitempty"`
	UpdatedAt *string                                                                      `json:"updated_at,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStageWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStageWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) SetId(v string) {
	o.Id = &v
}

// GetJobs returns the Jobs field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetJobs() []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob {
	if o == nil || IsNil(o.Jobs) {
		var ret []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob
		return ret
	}
	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetJobsOk() ([]GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob, bool) {
	if o == nil || IsNil(o.Jobs) {
		return nil, false
	}
	return o.Jobs, true
}

// HasJobs returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) HasJobs() bool {
	if o != nil && !IsNil(o.Jobs) {
		return true
	}

	return false
}

// SetJobs gets a reference to the given []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob and assigns it to the Jobs field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) SetJobs(v []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJob) {
	o.Jobs = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) SetName(v string) {
	o.Name = &v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) SetRunId(v string) {
	o.RunId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetStatus() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus {
	if o == nil || IsNil(o.Status) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetStatusOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus and assigns it to the Status field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) SetStatus(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelJobStatus) {
	o.Status = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Jobs) {
		toSerialize["jobs"] = o.Jobs
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RunId) {
		toSerialize["run_id"] = o.RunId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
