/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage struct {
	Branch       *string `json:"branch,omitempty"`
	Id           *string `json:"id,omitempty"`
	ManifestPath *string `json:"manifest_path,omitempty"`
	PipelineId   *string `json:"pipeline_id,omitempty"`
	RepositoryId *string `json:"repository_id,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorageWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorageWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage{}
	return &this
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) SetBranch(v string) {
	o.Branch = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) SetId(v string) {
	o.Id = &v
}

// GetManifestPath returns the ManifestPath field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetManifestPath() string {
	if o == nil || IsNil(o.ManifestPath) {
		var ret string
		return ret
	}
	return *o.ManifestPath
}

// GetManifestPathOk returns a tuple with the ManifestPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetManifestPathOk() (*string, bool) {
	if o == nil || IsNil(o.ManifestPath) {
		return nil, false
	}
	return o.ManifestPath, true
}

// HasManifestPath returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) HasManifestPath() bool {
	if o != nil && !IsNil(o.ManifestPath) {
		return true
	}

	return false
}

// SetManifestPath gets a reference to the given string and assigns it to the ManifestPath field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) SetManifestPath(v string) {
	o.ManifestPath = &v
}

// GetPipelineId returns the PipelineId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetPipelineId() string {
	if o == nil || IsNil(o.PipelineId) {
		var ret string
		return ret
	}
	return *o.PipelineId
}

// GetPipelineIdOk returns a tuple with the PipelineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetPipelineIdOk() (*string, bool) {
	if o == nil || IsNil(o.PipelineId) {
		return nil, false
	}
	return o.PipelineId, true
}

// HasPipelineId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) HasPipelineId() bool {
	if o != nil && !IsNil(o.PipelineId) {
		return true
	}

	return false
}

// SetPipelineId gets a reference to the given string and assigns it to the PipelineId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) SetPipelineId(v string) {
	o.PipelineId = &v
}

// GetRepositoryId returns the RepositoryId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetRepositoryId() string {
	if o == nil || IsNil(o.RepositoryId) {
		var ret string
		return ret
	}
	return *o.RepositoryId
}

// GetRepositoryIdOk returns a tuple with the RepositoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) GetRepositoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.RepositoryId) {
		return nil, false
	}
	return o.RepositoryId, true
}

// HasRepositoryId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) HasRepositoryId() bool {
	if o != nil && !IsNil(o.RepositoryId) {
		return true
	}

	return false
}

// SetRepositoryId gets a reference to the given string and assigns it to the RepositoryId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) SetRepositoryId(v string) {
	o.RepositoryId = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ManifestPath) {
		toSerialize["manifest_path"] = o.ManifestPath
	}
	if !IsNil(o.PipelineId) {
		toSerialize["pipeline_id"] = o.PipelineId
	}
	if !IsNil(o.RepositoryId) {
		toSerialize["repository_id"] = o.RepositoryId
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRepoConfigStorage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
