/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate struct {
	Deployment *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment `json:"deployment,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreateWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreateWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate{}
	return &this
}

// GetDeployment returns the Deployment field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) GetDeployment() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment {
	if o == nil || IsNil(o.Deployment) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment
		return ret
	}
	return *o.Deployment
}

// GetDeploymentOk returns a tuple with the Deployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) GetDeploymentOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment, bool) {
	if o == nil || IsNil(o.Deployment) {
		return nil, false
	}
	return o.Deployment, true
}

// HasDeployment returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) HasDeployment() bool {
	if o != nil && !IsNil(o.Deployment) {
		return true
	}

	return false
}

// SetDeployment gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment and assigns it to the Deployment field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) SetDeployment(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelDeployment) {
	o.Deployment = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deployment) {
		toSerialize["deployment"] = o.Deployment
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseDeploymentCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
