/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs struct {
	Message *string `json:"message,omitempty"`
	Time    *string `json:"time,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogsWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogsWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) SetMessage(v string) {
	o.Message = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) SetTime(v string) {
	o.Time = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
