/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList struct {
	Logs []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs `json:"logs,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogListWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogListWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList{}
	return &this
}

// GetLogs returns the Logs field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) GetLogs() []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs {
	if o == nil || IsNil(o.Logs) {
		var ret []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs
		return ret
	}
	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) GetLogsOk() ([]GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs, bool) {
	if o == nil || IsNil(o.Logs) {
		return nil, false
	}
	return o.Logs, true
}

// HasLogs returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) HasLogs() bool {
	if o != nil && !IsNil(o.Logs) {
		return true
	}

	return false
}

// SetLogs gets a reference to the given []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs and assigns it to the Logs field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) SetLogs(v []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogs) {
	o.Logs = v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Logs) {
		toSerialize["logs"] = o.Logs
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseJobLogList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
