/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest struct for GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest
type GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest struct {
	// Args contains arguments for message
	Arguments map[string]map[string]interface{} `json:"arguments,omitempty"`
	// Message is text that can be displayed to the user. It should not contain any specific background information about protocols, databases, programming languages, etc.
	Message *string `json:"message,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest() *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequestWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequestWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest{}
	return &this
}

// GetArguments returns the Arguments field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) GetArguments() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Arguments) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Arguments
}

// GetArgumentsOk returns a tuple with the Arguments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) GetArgumentsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Arguments) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Arguments, true
}

// HasArguments returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) HasArguments() bool {
	if o != nil && !IsNil(o.Arguments) {
		return true
	}

	return false
}

// SetArguments gets a reference to the given map[string]map[string]interface{} and assigns it to the Arguments field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) SetArguments(v map[string]map[string]interface{}) {
	o.Arguments = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) SetMessage(v string) {
	o.Message = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Arguments) {
		toSerialize["arguments"] = o.Arguments
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest(val *GitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalErrorsBadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
