/*
Pipelines Public API

Pipelines Public API

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package workflowclient

import (
	"encoding/json"
)

// checks if the GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet{}

// GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet struct for GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet
type GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet struct {
	Branch        *string                                                                      `json:"branch,omitempty"`
	CreatedAt     *string                                                                      `json:"created_at,omitempty"`
	Id            *string                                                                      `json:"id,omitempty"`
	Pipeline      *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline  `json:"pipeline,omitempty"`
	PipelineId    *string                                                                      `json:"pipeline_id,omitempty"`
	Snapshot      *string                                                                      `json:"snapshot,omitempty"`
	Stages        []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage    `json:"stages,omitempty"`
	Status        *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus `json:"status,omitempty"`
	StatusMessage *string                                                                      `json:"status_message,omitempty"`
	// TODO: Should we save this?
	TemporalRunId      *string `json:"temporal_run_id,omitempty"`
	TemporalWorkflowId *string `json:"temporal_workflow_id,omitempty"`
	UpdatedAt          *string `json:"updated_at,omitempty"`
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet{}
	return &this
}

// NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGetWithDefaults instantiates a new GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGetWithDefaults() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet {
	this := GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet{}
	return &this
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetBranch(v string) {
	o.Branch = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetId(v string) {
	o.Id = &v
}

// GetPipeline returns the Pipeline field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetPipeline() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline {
	if o == nil || IsNil(o.Pipeline) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline
		return ret
	}
	return *o.Pipeline
}

// GetPipelineOk returns a tuple with the Pipeline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetPipelineOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline, bool) {
	if o == nil || IsNil(o.Pipeline) {
		return nil, false
	}
	return o.Pipeline, true
}

// HasPipeline returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasPipeline() bool {
	if o != nil && !IsNil(o.Pipeline) {
		return true
	}

	return false
}

// SetPipeline gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline and assigns it to the Pipeline field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetPipeline(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelPipeline) {
	o.Pipeline = &v
}

// GetPipelineId returns the PipelineId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetPipelineId() string {
	if o == nil || IsNil(o.PipelineId) {
		var ret string
		return ret
	}
	return *o.PipelineId
}

// GetPipelineIdOk returns a tuple with the PipelineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetPipelineIdOk() (*string, bool) {
	if o == nil || IsNil(o.PipelineId) {
		return nil, false
	}
	return o.PipelineId, true
}

// HasPipelineId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasPipelineId() bool {
	if o != nil && !IsNil(o.PipelineId) {
		return true
	}

	return false
}

// SetPipelineId gets a reference to the given string and assigns it to the PipelineId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetPipelineId(v string) {
	o.PipelineId = &v
}

// GetSnapshot returns the Snapshot field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetSnapshot() string {
	if o == nil || IsNil(o.Snapshot) {
		var ret string
		return ret
	}
	return *o.Snapshot
}

// GetSnapshotOk returns a tuple with the Snapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetSnapshotOk() (*string, bool) {
	if o == nil || IsNil(o.Snapshot) {
		return nil, false
	}
	return o.Snapshot, true
}

// HasSnapshot returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasSnapshot() bool {
	if o != nil && !IsNil(o.Snapshot) {
		return true
	}

	return false
}

// SetSnapshot gets a reference to the given string and assigns it to the Snapshot field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetSnapshot(v string) {
	o.Snapshot = &v
}

// GetStages returns the Stages field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetStages() []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage {
	if o == nil || IsNil(o.Stages) {
		var ret []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage
		return ret
	}
	return o.Stages
}

// GetStagesOk returns a tuple with the Stages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetStagesOk() ([]GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage, bool) {
	if o == nil || IsNil(o.Stages) {
		return nil, false
	}
	return o.Stages, true
}

// HasStages returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasStages() bool {
	if o != nil && !IsNil(o.Stages) {
		return true
	}

	return false
}

// SetStages gets a reference to the given []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage and assigns it to the Stages field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetStages(v []GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelStage) {
	o.Stages = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetStatus() GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus {
	if o == nil || IsNil(o.Status) {
		var ret GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetStatusOk() (*GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus and assigns it to the Status field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetStatus(v GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationModelRunStatus) {
	o.Status = &v
}

// GetStatusMessage returns the StatusMessage field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetStatusMessage() string {
	if o == nil || IsNil(o.StatusMessage) {
		var ret string
		return ret
	}
	return *o.StatusMessage
}

// GetStatusMessageOk returns a tuple with the StatusMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetStatusMessageOk() (*string, bool) {
	if o == nil || IsNil(o.StatusMessage) {
		return nil, false
	}
	return o.StatusMessage, true
}

// HasStatusMessage returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasStatusMessage() bool {
	if o != nil && !IsNil(o.StatusMessage) {
		return true
	}

	return false
}

// SetStatusMessage gets a reference to the given string and assigns it to the StatusMessage field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetStatusMessage(v string) {
	o.StatusMessage = &v
}

// GetTemporalRunId returns the TemporalRunId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetTemporalRunId() string {
	if o == nil || IsNil(o.TemporalRunId) {
		var ret string
		return ret
	}
	return *o.TemporalRunId
}

// GetTemporalRunIdOk returns a tuple with the TemporalRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetTemporalRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemporalRunId) {
		return nil, false
	}
	return o.TemporalRunId, true
}

// HasTemporalRunId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasTemporalRunId() bool {
	if o != nil && !IsNil(o.TemporalRunId) {
		return true
	}

	return false
}

// SetTemporalRunId gets a reference to the given string and assigns it to the TemporalRunId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetTemporalRunId(v string) {
	o.TemporalRunId = &v
}

// GetTemporalWorkflowId returns the TemporalWorkflowId field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetTemporalWorkflowId() string {
	if o == nil || IsNil(o.TemporalWorkflowId) {
		var ret string
		return ret
	}
	return *o.TemporalWorkflowId
}

// GetTemporalWorkflowIdOk returns a tuple with the TemporalWorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetTemporalWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemporalWorkflowId) {
		return nil, false
	}
	return o.TemporalWorkflowId, true
}

// HasTemporalWorkflowId returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasTemporalWorkflowId() bool {
	if o != nil && !IsNil(o.TemporalWorkflowId) {
		return true
	}

	return false
}

// SetTemporalWorkflowId gets a reference to the given string and assigns it to the TemporalWorkflowId field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetTemporalWorkflowId(v string) {
	o.TemporalWorkflowId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Pipeline) {
		toSerialize["pipeline"] = o.Pipeline
	}
	if !IsNil(o.PipelineId) {
		toSerialize["pipeline_id"] = o.PipelineId
	}
	if !IsNil(o.Snapshot) {
		toSerialize["snapshot"] = o.Snapshot
	}
	if !IsNil(o.Stages) {
		toSerialize["stages"] = o.Stages
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusMessage) {
		toSerialize["status_message"] = o.StatusMessage
	}
	if !IsNil(o.TemporalRunId) {
		toSerialize["temporal_run_id"] = o.TemporalRunId
	}
	if !IsNil(o.TemporalWorkflowId) {
		toSerialize["temporal_workflow_id"] = o.TemporalWorkflowId
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet struct {
	value *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet
	isSet bool
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) Get() *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet {
	return v.value
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) Set(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) {
	v.value = val
	v.isSet = true
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) IsSet() bool {
	return v.isSet
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet(val *GitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet {
	return &NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet{value: val, isSet: true}
}

func (v NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitSbercloudTechDsworksServicesPipelineSrcInternalApplicationResponseRunGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
